# Site settings
title: Intro to Stat & Data Sciences
email: albert.ys.kim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An introduction to statistical and machine learning.
baseurl: /MATH116
url: https://rudeboybert.github.io
urllabel: "Albert Y. Kim's Webpage"

# Build settings
markdown: kramdown
github_username: rudeboybert
future: true
timezone: UTC+4
