# Site settings
title: Intro to Statistical and Data Sciences
email: albert.ys.kim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Combining statistical and computational thinking to make sense of data.
baseurl: /MATH116
url: https://rudeboybert.github.io
urllabel: "Albert Y. Kim's Webpage"

# Build settings
markdown: kramdown
github_username: rudeboybert
